[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://handsheet.netlify.app"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true

[[redirects]]
  from = "/api/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 204
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type", Access-Control-Allow-Credentials = "true"}
