[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]

[functions.timeout]
  external_node_modules = ["tesseract.js", "xlsx"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}

[[redirects]]
  from = "/api/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "GET, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}
