[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true

[[redirects]]
  from = "/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true 