[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle OPTIONS requests differently
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cors"
  status = 200
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

# Regular API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

# Headers for all paths
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"

# Specific headers for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
