[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]

[functions.timeout]
  external_node_modules = ["tesseract.js", "xlsx"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "*", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "https://handsheet.netlify.app", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "*", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400", Vary = "Origin"}
