[build]
  command = "npm install && npm run build:functions"
  functions = "functions-dist"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "xlsx"]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://handsheet.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/api/commands/ocr"
  to = "/.netlify/functions/ocr"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://handsheet.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://handsheet.netlify.app",
    Access-Control-Allow-Methods = "GET, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://handsheet.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  methods = ["OPTIONS"]
  headers = { 
    Access-Control-Allow-Origin = "https://handsheet.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization",
    Access-Control-Allow-Credentials = "true"
  } 